# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e5d5ef5e3b3767530a2585cd8486de43e2b54358ebced3170de01428fa17b5dd812d5cebaf2d693e1f8413fc92d7b75b8194fd201922de500714460027e7050d

test:
  secret_key_base: 6479c1c6d298bad10926945b105f71d131c8e738ee6e0440f4c966fdf8df00fb2e509a92c34744712d87d41e2cf6980c2a53f3c41c29dd2370c9dbbcfeaa1523

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
